version: '3.7'
services:
  registry:
    restart: always
    image: registry:2
    container_name: docker_register
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: ./auth/registry.htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: ./data
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    environment:
      - CERTBOT_EMAIL=mail@com.pl
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./.docker/nginx/conf.d:/etc/nginx/user_conf.d

volumes:
  nginx_secrets: